"""remove email column

Revision ID: 4e60ac03b611
Revises: 115d1ef8cd73
Create Date: 2026-02-23 17:35:20.055858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e60ac03b611'
down_revision: Union[str, Sequence[str], None] = '115d1ef8cd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
